### ISSUE TITLE
Can't get souls to drop. Assumed mod conflict.

### ISSUE THREAD

**Issue by DC010** [Safrodev/Archon#14]
Are there any mods known to stop souls from dropping? Do souls only drop from default mobs?

Specifically, I finally got the soul scythe, then went through a dungeon from a mod that had a high spawn rate and got 0 souls even after an estimated 300 kills.

So before I go trying to kill overworld mobs in a field and hoping for the best, I wanted to ask here.

Thank you

**Comment by Safrodev** [comment]
There aren't any mods I know of that stop souls from dropping. I believe you were killing mobs that don't drop souls (ex. undead mobs) which is why you weren't getting any. Please refer to this [link](https://github.com/Safrodev/Archon/blob/main/src/main/resources/data/archon/tags/entity_types/creatures.json) for creature souls and this [link](https://github.com/Safrodev/Archon/blob/main/src/main/resources/data/c/tags/entity_types/bosses.json) for boss souls. These tags can be edited to add/remove mobs using datapacks but they show the default list of mobs that drop souls.

**Comment by DC010** [comment]
Awesome, thank you.

Have you considered partnering with any of the mods that add bosses and
creatures to expand the list natively?

**Comment by Safrodev** [comment]
Yeah, I will add some native compat in the next update, though the bosses should be done from the other mod’s end since it uses a common tag. Mods like Bewitchment utilize the bosses tag so that mod should work, for example.
