### ISSUE TITLE
Inigo Boss Crash

### ISSUE THREAD

**Issue by Avemado** [Safrodev/Archon#36]
**Describe the Bug**
Disconnect from the server with Prominence II installed, when summoning and fighting the Inigo boss from the Archon mod Internal Exception: net.minecraft.class_148: Exception while adding particle

**Reproduction Steps**
1. Use Prominence II version 1.2.0
2. Summon Inigo
3. Fight Inigo
4. Get error and disconnect while fighting Inigo

**Screenshots and Videos**
![image](https://github.com/Safrodev/Archon/assets/58288858/47c44213-1e22-42ca-9a13-b0a018377335)

https://www.youtube.com/watch?v=CrzAzlhUe-E

**Crash Report or Log**
No response

**Operating System**
Windows 10/11

**Minecraft Version**
1.19

**Modloader**
Fabric

**Modpack Version**
1.2.0

**Optifine**
I used Optifine

**Other Mods**
No response

**Comment by Safrodev** [comment]
Interesting that there is no log this time. I thought I fixed this before but I guess not, will look into it

**Comment by Medusa1338** [comment]
Here to add a little more info and logs as this recently happened on my server (MC 1.20.1, Prominence II v1.3.1 FABRIC)

Three of my players were disconnected, and unable to reconnect, to the server after spawning Inigo. One of these three walked towards the Boss' location after it was spawned and received the same error upon seeing Inigo's health bar. Other players who were far enough away from the boss (outside of loading distance) were unaffected. Spawning the boss in creative mode did not cause this issue, presumably because it needs to attack/aggro before the bug occurs (as shown in @Avemado's video). 

Using the command "kill @e[type=archon:Inigo]" solved the issue and players were able to join again.

Below is a portion of my server's logs containing everything from the first disconnect occurring up until the boss was despawned.
https://pastebin.com/5UdjBhgK

This next paste is from one of our player's "latest.log" who was affected.  There was a lot but this portion seemed to be the most relevant - if anyone wants the full log please let me know. It contains a lot of errors related to one "safro.archon.client.particle.InfernoLaserParticle..." which is similar to the error @Avemado and all our affected players receive when trying to connect.
https://pastebin.com/LRqzrqs2

I hope this helps somehow!

**Comment by Safrodev** [comment]
Those logs were very helpful thank you. I think the bug is fixed in v0.5.5, let me know if it still crashes. I tested it on a server and everything seems to work.

**Comment by Medusa1338** [comment]
Updating to v0.5.5 solves the issue on my server. Thanks a lot, that was quick!

**Comment by Safrodev** [comment]
Awesome!
